// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbhktsqbcyosiviiydjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiaGt0c3FiY3lvc2l2aWl5ZGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDc1NTEsImV4cCI6MjA2ODc4MzU1MX0.3wh2H9V-FhNRF50drpbYfsJIQfI4S6nsAuy66rIwzlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});